<?php

declare(strict_types=1);

namespace App\AI\Agent\FixAgent;

use App\AI\LLM\LlmInterface;
use App\AI\Review\ReviewFinding;
use App\AI\Review\ReviewResult;

final class FixAgent implements FixAgentInterface
{
    public function __construct(
        private readonly LlmInterface $llm,
    ) {
    }

    public function fix(
        string $filePath,
        string $sourceCode,
        ReviewResult $reviewResult,
    ): string {
        if (!$reviewResult->hasFindings()) {
            return $sourceCode;
        }

        $prompt = $this->buildPrompt(
            $filePath,
            $sourceCode,
            $reviewResult->getFindings(),
        );

        error_log(sprintf(
            'FixAgent prompt size: %d bytes',
            strlen($prompt),
        ));

        return $this->llm->generate($prompt);
    }

    /**
     * @param ReviewFinding[] $findings
     */
    private function buildPrompt(
        string $filePath,
        string $sourceCode,
        array $findings,
    ): string {
        $review = [];

        foreach ($findings as $finding) {
            $review[] = sprintf(
                "- Line: %d\n  Severity: %s\n  Category: %s\n  Message: %s\n  Suggestion: %s",
                $finding->getLine(),
                $finding->getSeverity(),
                $finding->getCategory(),
                $finding->getMessage(),
                $finding->getSuggestion(),
            );
        }

        $reviewText = implode("\n", $review);

        return <<<PROMPT
You are an AI software engineer responsible for fixing source code.

You are Agent 2 in a two-agent code review and fix system.

The code review findings below were already generated by Agent 1 and explicitly approved by the developer.

Your task is to apply ONLY the approved findings.

IMPORTANT:
- Do NOT perform a new code review.
- Do NOT search for additional issues.
- Do NOT fix issues that are not listed below.
- Do NOT add improvements that were not requested.
- Do NOT change unrelated code.
- Do NOT reinterpret the review by inventing new findings.
- The approved findings are the complete scope of this fix.

Rules:
1. Return ONLY the complete corrected source code.
2. Do not return Markdown code fences.
3. Do not explain the changes.
4. Do not modify unrelated code.
5. Preserve the existing functionality unless a review finding requires a change.
6. Do not introduce new dependencies unless absolutely necessary.
7. Keep the existing coding style.
8. The returned result must be valid source code.
9. Apply all applicable approved review findings.
10. Make the smallest reasonable changes required to address the approved findings.

File:
{$filePath}

Current source code:
{$sourceCode}

Approved code review findings:
{$reviewText}

Return the complete corrected source code only.
PROMPT;
    }
}
